### ISSUE TITLE
LASTORDNO will not build.

### ISSUE THREAD

**Issue by SJLennon** [IBM/ibmi-bob#236] opened 2023-05-11 21:57 UTC
(Possibly should be in bob-recursive-example. )

All work done on the PUB400 and none on my Windows 10 PC, except for PuTTY.

Cloned bob-recursive-example to IFS
```
.export lib1=LENNONSB
cd /home/LENNONS/bob-recursive-example
makei build
Objects:             4 failed 112 succeed 116 total
 > Failed objects:    CHS.MODULE CHS.PGM DEU.MODULE DEU.PGM
Build Completed!
```
The 4 failures are expected due to an issue with target CCSID. 

**The LASTORDNO data area was not created.** 
 And I can find no references to it in the .logs streamfiles.

I made a small change to a comment in QDTASRC/LASTORDNO.DTAARA (using VS Code I must admit).
Try build again from PuTTY.
```
export lib1=LENNONSB
cd /home/LENNONS/bob-recursive-example
makei b -d  QDTASRC
> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmpvmowl5_k" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/src/mk/Makefile" dir_QDTASRC

Objects:             0 failed 0 succeed 0 total
Build Completed!
```
**LASTORDNO is still not built.** I'm stumped.

**Comment by edmundreinhardt** [comment] 2023-05-12 16:30
are you sure that LASTORDNO source was deployed to the IFS dir?

I typically do a `touch /home/LENNONS/bob-recursive-example/QDTASRC/LASTORDNO.DTAARA`

I will try to reproduce.

**Comment by SJLennon** [comment] 2023-05-13 14:06
I believe this is the LASTORDNO source:
![image](https://github.com/IBM/ibmi-bob/assets/67484051/a350536d-91b0-4c79-8fdc-ca630784a66b)

![image](https://github.com/IBM/ibmi-bob/assets/67484051/079dc3ec-f695-4488-8ce0-37fcb0ac525a)

**Comment by SJLennon** [comment] 2023-05-13 14:12
Tried "touch" and it still does not build.

**Comment by edmundreinhardt** [comment] 2023-05-15 10:58
Betraying my ignorance here,.  How do I get an SSH terminal to work with pub400
```
ssh reinhard@pub400.com
ssh: connect to host pub400.com port 22: Connection refused
```

**Comment by martintosney** [comment] 2023-05-15 11:06
They don't run the daemon on port 22 - you need to specify `-p 2222` on your ssh command

**Comment by worksofliam** [comment] 2023-07-05 19:02
Looks like this works:

```
makei b -d QDDSSRC
```

But not with `QDTASRC`:

```
makei b -d QDTASRC
```

**Comment by edmundreinhardt** [comment] 2023-07-06 20:00
I have reproduced the problem on my home machine as well.  The issue seems to do with DTAARA object type.  I will investigate
```
-bash-5.1$ makei c -f  QDTASRC/LASTORDNO.DTAARA
targets: LASTORDNO.DTA
> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmp4yddk5xa" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/src/mk/Makefile" LASTORDNO.DTA
make: 'LASTORDNO.DTA' is up to date.
Objects:             0 failed 0 succeed 0 total
Build Completed!
```
also fails when just focused on the DTAARA source or target
```
-bash-5.1$ makei b -t  LASTORDNO.DTAARA
> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmpmtatmzbg" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/src/mk/Makefile" LASTORDNO.DTAARA
make: *** No rule to make target 'LASTORDNO.DTAARA'.
Objects:             0 failed 0 succeed 0 total
Build Completed!
```

**Comment by edmundreinhardt** [comment] 2023-11-02 21:12
was fixed in July

**Closed by edmundreinhardt** 2023-11-02 21:12 UTC
