### ISSUE TITLE
Bob constructs invalid SAVOBJ comand

### ISSUE THREAD

**Issue by shane-smith-mn** [IBM/ibmi-bob#215] opened 2023-04-12 20:06 UTC
https://github.com/IBM/ibmi-bob/blob/9c0c41b19aff5db2f4cfb91d53e5ce460631f715/src/makei/crtfrmstmf.py#L199

**Comment by edmundreinhardt** [comment] 2023-04-15 02:54
Duplicate of https://github.com/IBM/ibmi-bob/issues/207

**Closed by edmundreinhardt** 2023-04-15 02:54 UTC
