### ISSUE TITLE
bob-recursive-example failing to build 

### ISSUE THREAD

**Issue by jonnyz32** [IBM/ibmi-bob#307] opened 2024-04-03 17:38 UTC
System: (v7r3)
Library to build in to: WDSCTEST
User: WDSCTEST

Bob-recursive-example failed to build.
Some snippets from log
```
                /QOpenSys/pkgs/bin/makei build

> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmp9xe89xjo" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/src/mk/Makefile" all
=== Creating RPG module [XML001.RPGLE]
crtrpgmod module(testbuild/XML001) srcstmf('/home/WDSCTEST/builds/bob-recursive-example/QRPGLESRC/XML001.RPGLE') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT(' ') TGTCCSID(297) TGTRLS() INCDIR('includes' 'QPROTOSRC') DEFINE()
✕ Failed to create XML001.MODULE!

CPFA0A9: Object not found.  Object is /QSYS.LIB/testbuild.LIB/EVFEVENT.FILE/XML001.MBR.
CPFA097: Object not copied.  Object is /QSYS.LIB/testbuild.LIB/EVFEVENT.FILE/XML001.MBR.
make: *** [/QOpenSys/pkgs/lib/bob/src/mk/Makefile:67: XML001.MODULE] Error 255
=== Creating RPG module [TXT001.RPGLE]
crtrpgmod module(testbuild/TXT001) srcstmf('/home/WDSCTEST/builds/bob-recursive-example/QRPGLESRC/TXT001.RPGLE') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT(' ') TGTCCSID(297) TGTRLS() INCDIR('includes' 'QPROTOSRC') DEFINE()
✕ Failed to create TXT001.MODULE!

CPFA0A9: Object not found.  Object is /QSYS.LIB/testbuild.LIB/EVFEVENT.FILE/TXT001.MBR.
CPFA097: Object not copied.  Object is /QSYS.LIB/testbuild.LIB/EVFEVENT.FILE/TXT001.MBR.
make: *** [/QOpenSys/pkgs/lib/bob/src/mk/Makefile:67: TXT001.MODULE] Error 255
=== Creating PF [SAMREF.PF] in testbuild
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid *JOB  -f /home/WDSCTEST/builds/bob-recursive-example/common/SAMREF.PF -o SAMREF -l testbuild -c CRTPF -p AUT() DLTPCT(*NONE) OPTION(*EVENTF *SRC *LIST) REUSEDLT(*NO) SIZE() TEXT(' ')
✓ SAMREF.FILE was created successfully!
```
xml001.slpf
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CPC2198: Current library changed to TESTBUILD.
CPC2196: Library TESTBUILD added to library list.

>> executing command: crtrpgmod module(testbuild/XML001) srcstmf('/home/WDSCTEST/builds/bob-recursive-example/QRPGLESRC/XML001.RPGLE') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT(' ') TGTCCSID(297) TGTRLS() INCDIR('includes' 'QPROTOSRC') DEFINE()
>> liblist: QSYS QSYS2 QHLPSYS QUSRSYS QSHELL TESTBUILD TESTBUILD QGPL QTEMP QDEVELOP QBLDSYS QBLDSYSR
>> executing time: 2024-04-03-12.16.17.00

RNS9309: Compilation failed. Module XML001 not created in library TESTBUILD.
RNS9309: Compilation failed. Module XML001 not created in library TESTBUILD.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Comment by edmundreinhardt** [comment] 2024-04-03 17:57
Can you also attach the XML001.splf from the .logs directory
You can see this from the IBM i Job Log view as well

**Comment by jonnyz32** [comment] 2024-04-03 18:50
@edmundreinhardt I added the snippet in my description. But here it is again
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CPC2198: Current library changed to TESTBUILD.
CPC2196: Library TESTBUILD added to library list.

>> executing command: crtrpgmod module(testbuild/XML001) srcstmf('/home/WDSCTEST/builds/bob-recursive-example/QRPGLESRC/XML001.RPGLE') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT(' ') TGTCCSID(297) TGTRLS() INCDIR('includes' 'QPROTOSRC') DEFINE()
>> liblist: QSYS QSYS2 QHLPSYS QUSRSYS QSHELL TESTBUILD TESTBUILD QGPL QTEMP QDEVELOP QBLDSYS QBLDSYSR
>> executing time: 2024-04-03-12.16.17.00

RNS9309: Compilation failed. Module XML001 not created in library TESTBUILD.
RNS9309: Compilation failed. Module XML001 not created in library TESTBUILD.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Comment by edmundreinhardt** [comment] 2024-04-03 22:15
OK, so it looks like a compilation failure.
You can look at XML001.evfeventf in the .evfeventf directory or just look at the problems view.
I suspect that the problem is that it is not find external files.

**Comment by edmundreinhardt** [comment] 2024-04-03 22:16
If so, we need to make sure they are in the dependencies for that XML001 entry in the Rules.mk

**Comment by edmundreinhardt** [comment] 2024-04-04 21:02
Hi Jonathan
After looking at your system, we determined that your COBOL PTFs were backlevel so the TGTCCSID parameter was not supported.
This was fixed by applying 
CPP: SI81472
Command: SI81473
Compiler: SI83056 

We also determined that your 5770WDS license had expired.

After addressing those issues, everything built cleanly
<img width="1167" alt="image" src="https://github.com/IBM/ibmi-bob/assets/11184579/088eb171-71f1-48ac-b0ce-cfef5b05c919">

**Closed by edmundreinhardt** 2024-04-04 21:02 UTC
Labels: bug

**Comment by jonnyz32** [comment] 2024-04-04 21:07
@edmundreinhardt  Thank you!
