### ISSUE TITLE
Index file extension still fails

### ISSUE THREAD

**Issue by Russ-illumifin** [IBM/ibmi-bob#350] opened 2024-11-05 03:02 UTC
I noticed I posted my other questions in the bob-recursive repo and should have put it here. So, I am putting this in the correct place.

I don't know why the index error keeps happening. I checked everything Edmund pointed out and I still get the "INDEX is not a recognized file extension" message. I deleted the anbenei1.index file, rebuilt the Rules.mk files, and it now fails on another index file, ancodesi0.index. I attached the output file.

I also run the action without Source Orbit with the same result. Here is the action command: OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei build

If you need more info or files from me, let me know.

```
Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 293, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 41, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 254, in handle_build
    build_env = BuildEnv([target], args.make_options, get_override_vars(args))
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 65, in __init__
    self._create_build_vars()
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 85, in _create_build_vars
    rules_mk = RulesMk.from_file(rules_mk_path,  self.src_dir, map(Path, self.iproj_json.include_path))
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 185, in from_file
    rules_mk = RulesMk.from_str(rules_mk_str, rules_mk_path.parent, src_dir, include_dirs)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 270, in from_str
    return RulesMk(subdir, rules, containing_dir)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 151, in __init__
    tgt_group = FILE_TARGETGROUPS_MAPPING[decompose_filename(rule.source_file)[-2]]
  File "/QOpenSys/pkgs/lib/bob/src/makei/utils.py", line 248, in decompose_filename
    raise ValueError(f"Cannot decomposite filename: {filename} as {ext} is not a recognized file extension")
ValueError: Cannot decomposite filename: ancodesi0.index as INDEX is not a recognized file extension

Fetching errors from .evfevent.
Failed to download a file after Action: No such file

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by Russ-illumifin** [comment] 2024-11-05 17:35
If there is any other way I can help work through this, I am available to do so. Here is some more information:

Here is the build action I am running:
```
{
    "extensions": [
      "GLOBAL"
    ],
    "name": "Build all",
    "command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei build",
    "environment": "pase",
    "deployFirst": true,
    "postDownload": [
      ".logs",
      ".evfevent"
    ]
  }
```

Here is the output of that build (which is the same as the SO build result without the messages from SO):
```
Running Action: Build all (9:58:29 AM)
Working directory: /home/rroberts/builds/migrateTest
Commands:
                OPT=*EVENTF BUILDLIB=anndevrr /QOpenSys/pkgs/bin/makei build

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 293, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 41, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 254, in handle_build
    build_env = BuildEnv([target], args.make_options, get_override_vars(args))
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 65, in __init__
    self._create_build_vars()
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 85, in _create_build_vars
    rules_mk = RulesMk.from_file(rules_mk_path,  self.src_dir, map(Path, self.iproj_json.include_path))
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 185, in from_file
    rules_mk = RulesMk.from_str(rules_mk_str, rules_mk_path.parent, src_dir, include_dirs)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 270, in from_str
    return RulesMk(subdir, rules, containing_dir)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 151, in __init__
    tgt_group = FILE_TARGETGROUPS_MAPPING[decompose_filename(rule.source_file)[-2]]
  File "/QOpenSys/pkgs/lib/bob/src/makei/utils.py", line 248, in decompose_filename
    raise ValueError(f"Cannot decomposite filename: {filename} as {ext} is not a recognized file extension")
ValueError: Cannot decomposite filename: ancodesi0.index as INDEX is not a recognized file extension

Fetching errors from .evfevent.
Failed to download a file after Action: No such file

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by Russ-illumifin** [comment] 2024-11-06 14:02
Here is a zip file containing the SQL source and Rules files.

[IndexFailure 2024-11-05.zip](https://github.com/user-attachments/files/17648088/IndexFailure.2024-11-05.zip)

**Comment by edmundreinhardt** [comment] 2024-11-08 11:21
This is the right repo for this issue.
Sanjula and I will look at it today.  Did you tell us which level of Bob you are at?
`yum list bob` on PASE command line
```
-bash-5.1$ yum list bob
Installed Packages
bob.ppc64                                         2.4.26-1                                          @ibmi-base
Available Packages
bob.ppc64                                         2.4.30-1                                          ibmi-base
```

**Comment by Russ-illumifin** [comment] 2024-11-08 12:17
Thanks Edmund. Here is the output of the yum command:
```
Terminal started. Thanks for using Code for IBM i
-bash-5.2$ yum list bob
Installed Packages
bob.ppc64                                                     2.4.30-1                                                      @ibmi-base
-bash-5.2$ 
```

If it helps to do an online session for you to debug it on my side, I can be available to do that.

**Comment by edmundreinhardt** [comment] 2024-11-08 12:33
Good news, I could reproduce the problem with your zip file

**Comment by edmundreinhardt** [comment] 2024-11-08 12:45
@irfanshar has already fixed this issue 4 months ago, but we have not released since then. 
So good news is that it is already fixed and that is why I could not reproduce it  on my local IBM i because it had those fixes.  
Bad news, you may have to wait a day or two for us to get another release out.

**Comment by Russ-illumifin** [comment] 2024-11-08 12:48
I'm glad you were able to reproduce it and know it was resolved. I will take it whenever it is available!

Thanks @edmundreinhardt and @irfanshar.

**Comment by Russ-illumifin** [comment] 2024-11-14 21:07
@edmundreinhardt do you have an estimate when the new updates will be available?

**Comment by edmundreinhardt** [comment] 2024-11-15 13:08
@Russ-illumifin I really thought I would have something out.  We have some other major enhancements and we just need to make sure that they are solid before they are released.  Looks like it might be another week depending on availability of our key resource. @irfanshar

**Comment by Russ-illumifin** [comment] 2024-11-15 16:36
Thanks for the update. I look forward to the enhancements!

**Comment by Russ-illumifin** [comment] 2024-11-26 17:28
@edmundreinhardt do you have another update on availability of the fix and enhancements?

**Comment by edmundreinhardt** [comment] 2024-11-26 18:10
Thanks for the reminder Russ.  We have a new enhancements that has a few bugs.  The developers are trying to get those fixed before we release.  You can follow it in the branch feature/wildcard-support
Sorry but all developers are currently pressed on other issues and didn't have time to get back to it this past week.   Hopefully within the coming week we can get that nailed down @SanjulaGanepola @irfanshar

**Comment by edmundreinhardt** [comment] 2024-12-06 13:48
Enhancement is tested and merged.  Now going to try to release.

**Comment by SanjulaGanepola** [comment] 2024-12-06 18:21
Hello @Russ-illumifin. Bob `v2.4.31` is out now can be updated via yum. Can you have a try with that version to see if it resolved your issue?

**Comment by Russ-illumifin** [comment] 2024-12-09 14:19
I will get the update and let you know how it goes. Thank you!

**Comment by Russ-illumifin** [comment] 2024-12-11 16:40
Thanks for fixing the file name problem! It is working for me now.

**Comment by edmundreinhardt** [comment] 2024-12-11 17:43
Fantastic

**Closed by edmundreinhardt** 2024-12-11 17:43 UTC

**Comment by rishabkaushik** [comment] 2025-07-25 08:07
@edmundreinhardt Thanks for the good work you and your team has put into this.

I am having a similar problem when compiling a single program using 

`makei compile -f aatestds.pgm.sqlrpgle`

Below is the traceback if the error.

`Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 293, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 41, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 236, in handle_compile
    build_env = BuildEnv(targets, args.make_options, get_override_vars(args))
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 65, in __init__
    self._create_build_vars()
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 85, in _create_build_vars
    rules_mk = RulesMk.from_file(rules_mk_path,  self.src_dir, map(Path, self.iproj_json.include_path))
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 185, in from_file
    rules_mk = RulesMk.from_str(rules_mk_str, rules_mk_path.parent, src_dir, include_dirs)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 353, in from_str
    return RulesMk(subdir, rules, containing_dir)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 151, in __init__
    tgt_group = FILE_TARGETGROUPS_MAPPING[decompose_filename(rule.source_file)[-2]]
  File "/QOpenSys/pkgs/lib/bob/src/makei/utils.py", line 250, in decompose_filename
    raise ValueError(f"Cannot decompose filename: {filename} as {ext} is not a recognized file extension")
ValueError: Cannot decompose filename: MYFILE.FILE as FILE is not a recognized file extension`

MYFILE is actually a PF.

I migrated a library to my local and trying to just build a single program first. The program aatestds.pgm.sqlrpgle does not even use it. I do not understand why it is trying to compile/do something with it. I understand it is not a normal workflow but I just wanted to compile a single object first before trying for a full build. 

I also had a look at https://github.com/IBM/ibmi-bob/blob/31e1df6e42fe85bb8a74d975d6d5d6120ff48504/src/makei/const.py#L103 and indeed it does not have FILE in it. FILE should be a valid extension if you are trying to compile a PF. 

The rules.mk for MYFILE has
`MYFILE.FILE: myfile.pf REFFIL.FILE`. Is this correct? 

AATESTDS.PGM.SQLRPGLE has below line in rules.mk
`AATESTDS.PGM: aatestds.pgm.sqlrpgle`

Do let me know if you have any questions.
