### ISSUE TITLE
CPD0018: String '+ ACTGRP(*' contains a character that is not valid.

### ISSUE THREAD

**Issue by SJLennon** [IBM/ibmi-bob#224] opened 2023-04-26 19:49 UTC
Bob version 2.4.11.  Running on PUB400.COM.  Using Code for IBM i.
Attempting to build bob-recursive-example from my PC folder.

Getting this error:
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CPC2198: Current library changed to LENNONSB.
CPC2196: Library LENNONSB added to library list.

>> executing command:  CRTSRVPGM SRVPGM(LENNONSB/FARTICLE) MODULE(ART300 ART301) BNDSRVPGM(FFAMILLY) +
ACTGRP(*CALLER) EXPORT(*ALL) TEXT('Function Aticle')
sed: The label :a;N;$!ba;s/\n/ /g is greater than eight characters.
>> liblist: 
>> executing time: 2023-04-26-19.19.01.%N

CPD0018: String '+ ACTGRP(*' contains a character that is not valid.
CPD0018: String ')         ' contains a character that is not valid.
CPF0006: Errors occurred in command.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


```
Complete joblog.json and output.json are attached. (Umm, seems like I can't attach JSON files. So they have to be TXT.)
[joblog.json.txt](https://github.com/IBM/ibmi-bob/files/11336695/joblog.json.txt)
[output.log.txt](https://github.com/IBM/ibmi-bob/files/11336697/output.log.txt)

**Comment by edmundreinhardt** [comment] 2023-04-27 13:51
Hmm it seems that the carriage returns are getting in there somehow and messing up the command string.
Are you running this from Windows using Code for IBM i extension in VS Code?
Tell me a little more about your environment. Because when I do a git clone and run from my Mac, I am not seeing this.

**Comment by edmundreinhardt** [comment] 2023-04-27 18:16
FYI Bob assumes all files are in UTF8.  I suspect this is why you are having some trouble with the bob-recursive-example

**Comment by SJLennon** [comment] 2023-04-27 18:39
I don't have Support EBCDIC checked. Seems unlikely that would have any impact since I'm working from a folder on my PC. Folder was created by cloning the bob-recursive project and I'm in the USA.
 Granted Code for IBM i is writing to the IFS when it uploads the source to PUB400 for the build, but is it doing any reading from the IFS that would make the Support EBCDIC option significant?

![image](https://user-images.githubusercontent.com/67484051/234959963-67710c18-f869-4df2-9b71-6bb00270f016.png)

**Comment by edmundreinhardt** [comment] 2023-04-27 19:29
@worksofliam Liam, under what circumstances does Code for IBM i not convert Windows line endings when deploying to the IFS.
@SJLennon I am assuming you did a deploy, or how were you invoking the  BOB build?
I am unable to reproduce this even with get cloning from https://github.com/IBM/bob-recursive-example.git onto a Windows machine with git set to windows line endings
I deploy to IFS and run the Code for IBM i command `err=*EVENTF lib1=&CURLIB makei build` and everthing built cleanly 
```
Objects:             0 failed 115 succeed 115 total
Build Completed!
```

**Comment by SJLennon** [comment] 2023-04-27 20:06
@edmundreinhardt 
I started out doing a "Build all" using the actions.json that Code for IBM i built for me.

**_I'll delete everything and start again, just in case I've done something strange. It's been known to happen..._**

This is what actions.json looks like:
[
  {
    "extensions": [
      "GLOBAL"
    ],
    "name": "Build all",
    "command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei build",
    "environment": "pase",
    "deployFirst": true,
    "postDownload": [
      ".logs/"
    ]
  },
  {
    "extensions": [
      "GLOBAL"
    ],
    "name": "Build current",
    "command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei compile -f &BASENAME",
    "environment": "pase",
    "deployFirst": true,
    "postDownload": [
      ".logs/"
    ]
  }
]

**Comment by SJLennon** [comment] 2023-04-28 19:40
**Starting over from scratch**
**_Summary:_**
1) Built project entirely on PUB400 (with no use of Code for IBM i). **Results: 4 failed 112 succeed 116 total.**
2) Cleaned everything up and repeated the process, this time using Code for IBM i.  **Results: 13 failed 103 succeed 116 total.**

So it looks like there is something quirky about Code for IBM i.
I'll post info on the various failure in subsequent comments.

**Comment by SJLennon** [comment] 2023-04-28 19:49
**_Creating completely on the IBM i_**. Using PuTTY client. Just 4 failures, which are both from the globalization directory.  (Don't under stand the strikethrough below, which I pasted from Notepad.)

 [~]$ md builds
-bash: md: command not found
 [~]$ mkdir builds
 [~]$ cd builds
 [~/builds]$ git clone https://github.com/IBM/bob-recursive-example
Cloning into 'bob-recursive-example'...
remote: Enumerating objects: 1031, done.
remote: Counting objects: 100% (1031/1031), done.
remote: Compressing objects: 100% (440/440), done.
remote: Total 1031 (delta 581), reused 1014 (delta 566), pack-reused 0
Receiving objects: 100% (1031/1031), 215.78 KiB | 2.05 MiB/s, done.
Resolving deltas: 100% (581/581), done.

 [~/builds]$ makei b -e lib1=lennonsb
 
=== Creating RPG module [CHS.RPGLE]
crtrpgmod module(lennonsb/CHS) srcstmf('/home/LENNONS/builds/bob-recursive-example/globalization/CHS/CHS.RPGLE') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT('') TGTCCSID(935) TGTRLS() INCDIR('includes' 'QPROTOSRC') DEFINE()
✕ Failed to create CHS.MODULE!

=== Creating program [CHS] from modules [CHS] and service programs []
crtpgm pgm(lennonsb/CHS) module(CHS) bndsrvpgm(*NONE) ACTGRP() USRPRF(*USER) TGTRLS() AUT() DETAIL(*EXTENDED) OPTION(*EVENTF) STGMDL(*SNGLVL) TEXT('')
✕ Failed to create CHS.PGM!

=== Creating RPG module [DEU.RPGLE]
crtrpgmod module(lennonsb/DEU) srcstmf('/home/LENNONS/builds/bob-recursive-example/globalization/DEU/DEU.RPGLE') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT('') TGTCCSID(273) TGTRLS() INCDIR('includes' 'QPROTOSRC') DEFINE()
✕ Failed to create DEU.MODULE!

=== Creating program [DEU] from modules [DEU] and service programs []
crtpgm pgm(lennonsb/DEU) module(DEU) bndsrvpgm(*NONE) ACTGRP() USRPRF(*USER) TGTRLS() AUT() DETAIL(*EXTENDED) OPTION(*EVENTF) STGMDL(*SNGLVL) TEXT('')
✕ Failed to create DEU.PGM!

**Objects:             4 failed 112 succeed 116 total**
 **> Failed objects:    CHS.MODULE CHS.PGM DEU.MODULE DEU.PGM**
Build Completed!
 [~/builds/bob-recursive-example]$

** Can't find any spool files for DEU. No idea why.
** CHS spool file is on hold on the PRT01 outq--different from all other spool files. iACS "Printer output" show it in chinese!
Green screen Display Spool File shows these errors:
                                                   -=* http://pub400.com *=-              
 5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONSB/CHS             PUB400 
Line   <---------------------- Source Specifications ----------------------------><---- Co
Number ....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8....+...
                          S o u r c e   L i s t i n g                                     
     1 /DEFINE DEF1                                                              should no
======>a                                                                                  
*RNF0257 30 a      000001  Form-Type entry for main procedure not valid or out of         
                           sequence.                                                      
     2 D fld2            s             20A     ccsid(*JOBRUNMIX)                          
     3   dcl-s fld3 char(30) ; // prompt before dcl-s should see all dcl-xx opcodes       
     4 C     '     ~         'cat       '   '        fld2                                 
======>                    aaaaaa                                                         
*RNF5014 30 a      000004  Operation code is not valid; specification is ignored.         
     5  fld2 = '      '; // hover on fld2 should work and should be seen as a reference   
======>a                                                                                  
*RNF0257 30 a      000005  Form-Type entry for main procedure not valid or out of         
                           sequence.                                                      
     6  //<- prompting here should see all calc opcodes                                   

Maybe the special characters at the beginning of the lines at throwing something off?
![image](https://user-images.githubusercontent.com/67484051/235239638-ce3202a4-1c90-46ca-a913-9f818141c482.png)

**Comment by worksofliam** [comment] 2023-04-28 20:54
@edmundreinhardt 

> Liam, under what circumstances does Code for IBM i not convert Windows line endings when deploying to the IFS.

It does not touch the file content at all and does not change line endings. It uploads the files as they are stored on the client.

**Comment by edmundreinhardt** [comment] 2023-04-28 21:31
As Liam says the deploy from your Windows PC to the IFS dir does not fix the line ending from Windows \r\n to the *nix \n
I suspect that you have your git setting to clone using \r\n and to fix to \n when pushing.,
But when you deploy to IBM i, is still \r\n which is causing the problem you are seeing.
Look on the status to see if for SAMPLE.BNDDIRSRC it is LF or CRLF
<img width="658" alt="image" src="https://user-images.githubusercontent.com/11184579/235255215-8b8ac379-da08-4abc-9f22-662383901530.png">

Just click on the CRLF and change to LF, redeploy and see if that fixed the problem.

**Comment by edmundreinhardt** [comment] 2023-04-29 00:42
The 4 failures when cloning directly to IBM i is due to the TGTCCSID override in .ibmi.json not taking effect as documented in issue 220.  Fix has been written and will be integrated soon

**Comment by edmundreinhardt** [comment] 2023-04-29 00:47
To solve the problem for Code for IBM i VS Code
change your global git config to
`git config --global core.autocrlf input`
Then all the line endings will be LF even in Windows after cloning.

The long term solution is for Code for IBM i deploy to change line endings.  Opening an issue on vscode-ibmi would help make this happen.

**Comment by SJLennon** [comment] 2023-04-29 21:42
> To solve the problem for Code for IBM i VS Code change your global git config to `git config --global core.autocrlf input` Then all the line endings will be LF even in Windows after cloning.
> 
> The long term solution is for Code for IBM i deploy to change line endings. Opening an issue on vscode-ibmi would help make this happen.

@edmundreinhardt 
Thanks for the help.  Setting `git config --global core.autocrlf input` works a whole lot better!
(However, it seems that only the service programs were impacted, so maybe something in the way you are handle pseudo source.)

**Comment by edmundreinhardt** [comment] 2023-07-06 20:06
Sam can I close this defect now? I am now working on LASTORDNO separatetly.

**Closed** 2023-07-06 21:01 UTC
